apiVersion: app/v1
kind: Deployment
metadata:
  name: codis-fe
  namespace: jcptb
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      name: codis-fe
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: codis-fe
    spec:
      imagePullSecrets:
      - name: myregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      containers:
      - name: codis-fe
        image: codis-image
        imagePullPolicy: IfNotPresent
        command: ["codis-fe"]
        args: ["-l","log/$(POD_NAME).log","--zookeeper","$(ZK_ADDR)","--listen=$(POD_IP):8080","--assets=$(CODIS_PATH)/bin/assets"]
        env:
        - name: CODIS_PATH
          value: "/gopath/src/github.com/CodisLabs/codis"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ZK_ADDR
          value: "zookeeper:2181"
        ports:
        - containerPort: 8080
          name: fe
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "200m"
            memory: 2Gi
